-- =====================================================================
--  Bookera — starter catalogue (generated 2026-09-27 by npm run db:seed-sql)
--  Import AFTER schema.sql.  Contains: 12 categories, 10 authors, 26 books.
--  The demo books are placeholders — replace them with your real titles from the admin panel.
--  file_path is the expected file name inside storage/books/ (upload the PDF/EPUB there).
-- =====================================================================

SET NAMES utf8mb4;
SET time_zone = '+00:00';
START TRANSACTION;

INSERT INTO categories (slug, name, description, tone, sort_order) VALUES
  ('programming', 'Programming', 'Learn programming, software development, frameworks, and modern technologies.', '#3654FF', 10),
  ('artificial-intelligence', 'Artificial Intelligence', 'Machine learning, generative AI, and the ideas shaping intelligent systems.', '#14171B', 20),
  ('technology', 'Technology', 'The products, platforms, and trends changing how we live and work.', '#2440E6', 30),
  ('business', 'Business', 'Strategy, marketing, leadership, and the craft of building great companies.', '#FF5D5D', 40),
  ('education', 'Education', 'Study skills, learning science, and guides for students and teachers.', '#0E7C7B', 50),
  ('self-development', 'Self Development', 'Habits, focus, and mindset for a more intentional life.', '#FFAE1F', 60),
  ('fiction', 'Fiction', 'Novels and stories that move, surprise, and stay with you.', '#7A5AF8', 70),
  ('science', 'Science', 'Physics, biology, and space — explained with clarity and wonder.', '#1F8A5B', 80),
  ('finance', 'Finance', 'Personal finance, investing, and money skills that compound.', '#9A5D00', 90),
  ('design', 'Design', 'Interface design, typography, and product thinking for makers.', '#C62F2F', 100),
  ('history', 'History', 'The people, places, and turning points that shaped our world.', '#5B4636', 110),
  ('entrepreneurship', 'Entrepreneurship', 'Playbooks for founders — from first idea to first thousand customers.', '#14171B', 120);

INSERT INTO authors (slug, name, specialization, bio, city, tone) VALUES
  ('alex-morgan', 'Alex Morgan', 'Software Engineer & Author', 'Writing about modern software development and emerging technologies.', 'Bengaluru', '#3654FF'),
  ('sophia-williams', 'Sophia Williams', 'Brand Strategist', 'Helping creators and founders build brands people remember and trust.', 'London', '#FF5D5D'),
  ('daniel-carter', 'Daniel Carter', 'AI Researcher', 'Explaining machine learning and the future of intelligent systems in plain language.', 'Toronto', '#14171B'),
  ('michael-brown', 'Michael Brown', 'Investor & Finance Educator', 'Making personal finance and long-term investing approachable for everyone.', 'New York', '#1F8A5B'),
  ('emma-wilson', 'Emma Wilson', 'Novelist', 'Writing quiet, character-driven fiction about cities, memory, and second chances.', 'Dublin', '#FFAE1F'),
  ('ryan-thomas', 'Ryan Thomas', 'Product Designer', 'Sharing practical systems for interface design, typography, and product thinking.', 'Berlin', '#7A5AF8'),
  ('priya-nair', 'Priya Nair', 'Educator & Learning Scientist', 'Researching how people learn — and turning that research into better study habits.', 'Kochi', '#0E7C7B'),
  ('kenji-watanabe', 'Kenji Watanabe', 'Physicist & Science Writer', 'Making the universe feel a little less distant, one chapter at a time.', 'Kyoto', '#2440E6'),
  ('lena-fischer', 'Lena Fischer', 'Historian', 'Telling the stories of trade, technology, and the ideas that shaped our world.', 'Vienna', '#9A5D00'),
  ('arjun-mehta', 'Arjun Mehta', 'Founder & Startup Mentor', 'Two-time founder writing honest playbooks for early-stage builders.', 'Mumbai', '#C62F2F');

INSERT INTO books (slug, title, subtitle, author_id, category_id, short_description, description, pages, language, format,
                   isbn, published_on, level, price_paise, is_free, status, is_enabled, is_featured, cover_design,
                   file_path, tags, learn, requirements) VALUES
  ('modern-javascript-development', 'Modern JavaScript Development', NULL, (SELECT id FROM authors WHERE slug = 'alex-morgan'), (SELECT id FROM categories WHERE slug = 'programming'), 'A practical guide to writing clean, fast, and maintainable JavaScript for the modern web.', 'From ES modules and async patterns to tooling, testing, and performance, this book walks you through the JavaScript that real teams ship today. Each chapter pairs a core concept with a small, working project so ideas turn into habits.', 320, 'English', 'pdf', '978-1-00000-101-4', '2026-03-14', 'Intermediate', 39900, 0, 'published', 1, 1, '{"bg":"#14171B","fg":"#F6F4EE","accent":"#FFAE1F","pattern":"code"}', 'modern-javascript-development.pdf', '["javascript","web","frontend"]', '["Write modern, modular JavaScript with confidence","Master async/await, promises, and the event loop","Set up fast tooling with bundlers and linters","Test and profile code like a senior engineer"]', '["Basic HTML & CSS","A code editor and a modern browser"]'),
  ('ai-and-the-future-of-technology', 'AI & The Future of Technology', NULL, (SELECT id FROM authors WHERE slug = 'daniel-carter'), (SELECT id FROM categories WHERE slug = 'artificial-intelligence'), 'How intelligent systems work, where they are heading, and what that means for all of us.', 'A clear-eyed tour of modern AI — from neural networks and large language models to the ethics, economics, and design questions they raise. Written for curious readers, not just engineers.', 286, 'English', 'pdf', '978-1-00000-102-1', '2026-05-02', 'All levels', 44900, 0, 'published', 1, 1, '{"bg":"#3654FF","fg":"#FFFFFF","accent":"#FFAE1F","pattern":"orbit"}', 'ai-and-the-future-of-technology.pdf', '["ai","machine learning","future"]', '["Understand how modern AI models are trained","Separate real capabilities from hype","Think critically about AI ethics and safety","Spot opportunities AI creates in your field"]', NULL),
  ('build-your-personal-brand', 'Build Your Personal Brand', NULL, (SELECT id FROM authors WHERE slug = 'sophia-williams'), (SELECT id FROM categories WHERE slug = 'business'), 'A step-by-step system for turning your expertise into a brand that opens doors.', 'Whether you are a student, freelancer, or founder, your reputation compounds. This book gives you a repeatable framework for positioning, storytelling, and showing up consistently online.', 210, 'English', 'epub', '978-1-00000-103-8', '2025-11-20', 'Beginner', 29900, 0, 'published', 1, 1, '{"bg":"#FFAE1F","fg":"#14171B","accent":"#FF5D5D","pattern":"sun"}', 'build-your-personal-brand.epub', '["branding","career","marketing"]', '["Define a clear, memorable positioning","Tell stories that make your work stick","Build a content rhythm you can sustain","Turn attention into real opportunities"]', NULL),
  ('typescript-in-practice', 'TypeScript in Practice', NULL, (SELECT id FROM authors WHERE slug = 'alex-morgan'), (SELECT id FROM categories WHERE slug = 'programming'), 'Type-safe patterns for real-world apps — without the ceremony.', 'Learn the parts of TypeScript that pay off every day: inference, narrowing, generics, and API design. Includes migration strategies for large JavaScript codebases.', 268, 'English', 'pdf', '978-1-00000-104-5', '2026-07-18', 'Intermediate', 34900, 0, 'published', 1, 0, '{"bg":"#2440E6","fg":"#FFFFFF","accent":"#F6F4EE","pattern":"grid"}', 'typescript-in-practice.pdf', '["typescript","javascript"]', '["Model data with precise types","Use generics without fear","Migrate a JS codebase incrementally","Design type-safe APIs"]', '["Comfort with JavaScript"]'),
  ('python-for-everyone', 'Python for Everyone', NULL, (SELECT id FROM authors WHERE slug = 'priya-nair'), (SELECT id FROM categories WHERE slug = 'programming'), 'A friendly first programming book, built around small projects you will actually finish.', 'Start from zero and build real things — a budget tracker, a quiz game, a tiny web scraper. Designed for students and career-switchers who learn best by doing.', 240, 'English', 'pdf', '978-1-00000-105-2', '2024-09-05', 'Beginner', 0, 1, 'published', 1, 0, '{"bg":"#F6F4EE","fg":"#14171B","accent":"#3654FF","pattern":"blocks"}', 'python-for-everyone.pdf', '["python","beginner"]', '["Think like a programmer","Write clean Python from day one","Work with files and data","Build five small projects"]', NULL),
  ('prompt-craft', 'Prompt Craft', 'Working well with language models', (SELECT id FROM authors WHERE slug = 'daniel-carter'), (SELECT id FROM categories WHERE slug = 'artificial-intelligence'), 'Practical techniques for getting reliable, useful results from AI assistants.', 'A hands-on field guide to prompting, evaluation, and building small AI-powered workflows. Full of before-and-after examples you can adapt immediately.', 184, 'English', 'epub', '978-1-00000-106-9', '2026-08-10', 'All levels', 24900, 0, 'published', 1, 0, '{"bg":"#FF5D5D","fg":"#FFFFFF","accent":"#14171B","pattern":"wave"}', 'prompt-craft.epub', '["ai","prompting","productivity"]', '["Structure prompts for consistent output","Evaluate AI responses systematically","Automate everyday knowledge work","Know when not to use AI"]', NULL),
  ('the-cloud-native-handbook', 'The Cloud-Native Handbook', NULL, (SELECT id FROM authors WHERE slug = 'alex-morgan'), (SELECT id FROM categories WHERE slug = 'technology'), 'Containers, deployments, and observability — explained for builders.', 'A grounded introduction to modern infrastructure. Understand what happens between git push and production, and how to keep systems healthy once they are there.', 298, 'English', 'pdf', '978-1-00000-107-6', '2025-06-22', 'Advanced', 39900, 0, 'published', 0, 0, '{"bg":"#0E7C7B","fg":"#F6F4EE","accent":"#FFAE1F","pattern":"stripes"}', 'the-cloud-native-handbook.pdf', '["cloud","devops"]', '["Containerise any app","Design safe deployment pipelines","Monitor what matters","Reason about cost and scale"]', '["Command-line basics","Some backend experience"]'),
  ('the-quiet-internet', 'The Quiet Internet', NULL, (SELECT id FROM authors WHERE slug = 'ryan-thomas'), (SELECT id FROM categories WHERE slug = 'technology'), 'Essays on attention, software, and designing technology that respects people.', 'A thoughtful collection of essays on building calmer products — and on living well alongside the devices in our pockets.', 176, 'English', 'epub', '978-1-00000-108-3', '2025-02-11', 'All levels', 19900, 0, 'published', 1, 0, '{"bg":"#EFECE3","fg":"#14171B","accent":"#FF5D5D","pattern":"dots"}', 'the-quiet-internet.epub', '["essays","attention","product"]', '["Recognise attention-extracting patterns","Design with restraint","Build healthier digital habits"]', NULL),
  ('zero-to-first-customer', 'Zero to First Customer', NULL, (SELECT id FROM authors WHERE slug = 'arjun-mehta'), (SELECT id FROM categories WHERE slug = 'entrepreneurship'), 'An honest playbook for validating ideas and landing your first paying users.', 'Skip the theory. This book covers customer interviews, scrappy MVPs, pricing experiments, and the uncomfortable conversations every founder must learn to have.', 224, 'English', 'pdf', '978-1-00000-109-0', '2026-01-28', 'Beginner', 34900, 0, 'published', 1, 1, '{"bg":"#14171B","fg":"#F6F4EE","accent":"#FF5D5D","pattern":"arch"}', 'zero-to-first-customer.pdf', '["startups","validation","sales"]', '["Run customer interviews that reveal truth","Ship an MVP in weeks, not months","Price with confidence","Close your first ten customers"]', NULL),
  ('the-learning-code', 'The Learning Code', NULL, (SELECT id FROM authors WHERE slug = 'priya-nair'), (SELECT id FROM categories WHERE slug = 'education'), 'Science-backed study techniques to learn faster and remember longer.', 'Spaced repetition, retrieval practice, interleaving — explained simply, with weekly plans for exams, languages, and new skills.', 196, 'English', 'pdf', '978-1-00000-110-6', '2025-08-14', 'All levels', 0, 1, 'published', 1, 1, '{"bg":"#1F8A5B","fg":"#FFFFFF","accent":"#FFAE1F","pattern":"rings"}', 'the-learning-code.pdf', '["study","learning","students"]', '["Study in less time with better results","Build a spaced-repetition system","Beat procrastination before exams","Take notes that you reuse"]', NULL),
  ('deep-focus', 'Deep Focus', NULL, (SELECT id FROM authors WHERE slug = 'sophia-williams'), (SELECT id FROM categories WHERE slug = 'self-development'), 'Reclaim your attention and do the most meaningful work of your life.', 'A calm, practical book about focus in a distracted age — with rituals, environment design, and weekly reviews that make deep work the default.', 204, 'English', 'epub', '978-1-00000-111-3', '2024-12-03', 'All levels', 24900, 0, 'published', 1, 0, '{"bg":"#F6F4EE","fg":"#14171B","accent":"#FFAE1F","pattern":"sun"}', 'deep-focus.epub', '["focus","habits","productivity"]', '["Design a distraction-resistant day","Build rituals for deep work","Run a weekly review that sticks"]', NULL),
  ('small-habits-big-years', 'Small Habits, Big Years', NULL, (SELECT id FROM authors WHERE slug = 'priya-nair'), (SELECT id FROM categories WHERE slug = 'self-development'), 'Tiny routines that quietly compound into a life you are proud of.', 'A gentle, evidence-informed approach to habit change, with worksheets for sleep, movement, reading, and money.', 168, 'English', 'pdf', '978-1-00000-112-0', '2023-10-19', 'Beginner', 0, 1, 'published', 1, 0, '{"bg":"#FFAE1F","fg":"#14171B","accent":"#1F8A5B","pattern":"blocks"}', 'small-habits-big-years.pdf', '["habits","wellbeing"]', '["Design habits that survive bad days","Track progress without obsession","Recover quickly from setbacks"]', NULL),
  ('the-lantern-house', 'The Lantern House', NULL, (SELECT id FROM authors WHERE slug = 'emma-wilson'), (SELECT id FROM categories WHERE slug = 'fiction'), 'A family, a seaside guesthouse, and one summer that changes everything.', 'When Nora returns to the guesthouse her grandmother ran for forty years, she finds letters that rewrite everything she believed about her family. A warm, bittersweet novel about home and forgiveness.', 352, 'English', 'epub', '978-1-00000-113-7', '2025-05-09', 'All levels', 29900, 0, 'published', 1, 1, '{"bg":"#14171B","fg":"#FFAE1F","accent":"#FFAE1F","pattern":"arch"}', 'the-lantern-house.epub', '["literary fiction","family"]', '["A story of memory, family, and forgiveness","Told across two timelines","Perfect for book clubs"]', NULL),
  ('signals-from-orion', 'Signals from Orion', NULL, (SELECT id FROM authors WHERE slug = 'emma-wilson'), (SELECT id FROM categories WHERE slug = 'fiction'), 'A near-future mystery about a radio astronomer and a message no one can explain.', 'Late one night, a small observatory receives a pattern that should not exist. A tense, humane science-fiction story about curiosity and connection.', 312, 'English', 'pdf', '978-1-00000-114-4', '2026-06-01', 'All levels', 24900, 0, 'published', 1, 0, '{"bg":"#2440E6","fg":"#F6F4EE","accent":"#FFAE1F","pattern":"orbit"}', 'signals-from-orion.pdf', '["sci-fi","mystery"]', '["A page-turning near-future mystery","Grounded, science-inspired storytelling"]', NULL),
  ('money-made-simple', 'Money Made Simple', NULL, (SELECT id FROM authors WHERE slug = 'michael-brown'), (SELECT id FROM categories WHERE slug = 'finance'), 'Budgeting, saving, and investing — the no-jargon guide for your first salary.', 'Everything nobody told you about money: emergency funds, index funds, taxes, and building wealth slowly and safely.', 232, 'English', 'pdf', '978-1-00000-115-1', '2025-03-30', 'Beginner', 19900, 0, 'published', 1, 0, '{"bg":"#1F8A5B","fg":"#F6F4EE","accent":"#F6F4EE","pattern":"stripes"}', 'money-made-simple.pdf', '["personal finance","investing"]', '["Build a budget you will keep","Create an emergency fund","Understand index investing","Avoid common money traps"]', NULL),
  ('the-long-game-investor', 'The Long-Game Investor', NULL, (SELECT id FROM authors WHERE slug = 'michael-brown'), (SELECT id FROM categories WHERE slug = 'finance'), 'Patient strategies for building wealth over decades, not days.', 'A practical framework for long-term investing: asset allocation, behaviour, and staying calm when markets are not.', 276, 'English', 'pdf', '978-1-00000-116-8', '2026-04-12', 'Intermediate', 39900, 0, 'published', 1, 0, '{"bg":"#F6F4EE","fg":"#14171B","accent":"#1F8A5B","pattern":"wave"}', 'the-long-game-investor.pdf', '["investing","wealth"]', '["Design a simple portfolio","Manage risk with allocation","Avoid behavioural mistakes"]', NULL),
  ('interface-systems', 'Interface Systems', NULL, (SELECT id FROM authors WHERE slug = 'ryan-thomas'), (SELECT id FROM categories WHERE slug = 'design'), 'Build design systems that scale — tokens, components, and the rules between them.', 'From spacing scales to component APIs, learn how leading product teams create consistent, flexible interfaces.', 258, 'English', 'pdf', '978-1-00000-117-5', '2026-02-17', 'Intermediate', 44900, 0, 'published', 1, 1, '{"bg":"#FF5D5D","fg":"#14171B","accent":"#F6F4EE","pattern":"grid"}', 'interface-systems.pdf', '["design systems","ui","product"]', '["Define tokens for colour, type, and spacing","Design flexible component APIs","Document systems people use","Scale design across teams"]', NULL),
  ('type-on-screen', 'Type on Screen', NULL, (SELECT id FROM authors WHERE slug = 'ryan-thomas'), (SELECT id FROM categories WHERE slug = 'design'), 'A modern handbook of typography for websites, apps, and digital products.', 'Choose, pair, and set type that reads beautifully on every screen. Covers hierarchy, rhythm, variable fonts, and accessibility.', 190, 'English', 'epub', '978-1-00000-118-2', '2024-07-08', 'All levels', 29900, 0, 'published', 1, 0, '{"bg":"#F6F4EE","fg":"#14171B","accent":"#FF5D5D","pattern":"blocks"}', 'type-on-screen.epub', '["typography","ui"]', '["Pair typefaces with intent","Build a clear type scale","Set readable, accessible text"]', NULL),
  ('the-universe-in-ten-ideas', 'The Universe in Ten Ideas', NULL, (SELECT id FROM authors WHERE slug = 'kenji-watanabe'), (SELECT id FROM categories WHERE slug = 'science'), 'From quantum fields to cosmic expansion — the big ideas of physics, made clear.', 'Ten short, beautifully explained chapters on the ideas that describe our universe. No equations required — just curiosity.', 214, 'English', 'pdf', '978-1-00000-119-9', '2025-09-25', 'All levels', 34900, 0, 'published', 1, 0, '{"bg":"#14171B","fg":"#F6F4EE","accent":"#3654FF","pattern":"rings"}', 'the-universe-in-ten-ideas.pdf', '["physics","space"]', '["Grasp relativity intuitively","Understand the quantum world","See how the universe evolves"]', NULL),
  ('life-in-the-cell', 'Life in the Cell', NULL, (SELECT id FROM authors WHERE slug = 'kenji-watanabe'), (SELECT id FROM categories WHERE slug = 'science'), 'A visual journey into the tiny machines that keep every living thing alive.', 'An accessible introduction to cell biology, from DNA to proteins, written for students and lifelong learners.', 188, 'English', 'pdf', '978-1-00000-120-5', '2024-03-15', 'Beginner', 0, 1, 'published', 1, 0, '{"bg":"#0E7C7B","fg":"#FFFFFF","accent":"#FFAE1F","pattern":"dots"}', 'life-in-the-cell.pdf', '["biology","students"]', '["Understand how cells work","Explain DNA and proteins simply","Prepare for biology exams"]', NULL),
  ('silk-steam-and-silicon', 'Silk, Steam & Silicon', NULL, (SELECT id FROM authors WHERE slug = 'lena-fischer'), (SELECT id FROM categories WHERE slug = 'history'), 'How trade routes and inventions connected the world — from caravans to chips.', 'A sweeping, readable history of technology and commerce, tracing the threads that link ancient markets to modern networks.', 364, 'English', 'pdf', '978-1-00000-121-2', '2025-01-14', 'All levels', 39900, 0, 'published', 1, 0, '{"bg":"#9A5D00","fg":"#F6F4EE","accent":"#FFAE1F","pattern":"stripes"}', 'silk-steam-and-silicon.pdf', '["history","technology","trade"]', '["Trace technology across civilisations","See how trade shaped ideas","Connect history to today"]', NULL),
  ('marketing-that-matters', 'Marketing That Matters', NULL, (SELECT id FROM authors WHERE slug = 'sophia-williams'), (SELECT id FROM categories WHERE slug = 'business'), 'Honest marketing for small teams: positioning, content, and growth loops.', 'A modern marketing playbook for startups and small businesses who want to grow without shouting.', 246, 'English', 'epub', '978-1-00000-122-9', '2026-09-02', 'Intermediate', 34900, 0, 'published', 1, 0, '{"bg":"#3654FF","fg":"#FFFFFF","accent":"#FF5D5D","pattern":"blocks"}', 'marketing-that-matters.epub', '["marketing","growth"]', '["Position a product clearly","Build a content engine","Design simple growth loops"]', NULL),
  ('founder-notes', 'Founder Notes', NULL, (SELECT id FROM authors WHERE slug = 'arjun-mehta'), (SELECT id FROM categories WHERE slug = 'entrepreneurship'), 'Short, candid lessons on hiring, fundraising, and staying sane as a founder.', 'Fifty short chapters drawn from building two companies — what worked, what failed, and what the author would do differently.', 198, 'English', 'pdf', '978-1-00000-123-6', '2024-11-11', 'All levels', 0, 1, 'published', 1, 0, '{"bg":"#FFAE1F","fg":"#14171B","accent":"#14171B","pattern":"grid"}', 'founder-notes.pdf', '["startups","leadership"]', '["Hire your first team","Prepare for a fundraise","Protect your energy as a founder"]', NULL),
  ('teaching-with-technology', 'Teaching with Technology', NULL, (SELECT id FROM authors WHERE slug = 'priya-nair'), (SELECT id FROM categories WHERE slug = 'education'), 'A classroom-tested guide to using digital tools that genuinely help students learn.', 'For teachers and educators who want to use technology thoughtfully — with lesson templates, assessment ideas, and case studies.', 222, 'English', 'pdf', '978-1-00000-124-3', '2025-07-07', 'Intermediate', 19900, 0, 'published', 0, 0, '{"bg":"#EFECE3","fg":"#14171B","accent":"#0E7C7B","pattern":"code"}', 'teaching-with-technology.pdf', '["teaching","edtech"]', '["Choose tools with purpose","Design blended lessons","Assess learning digitally"]', NULL),
  ('react-patterns-2027', 'React Patterns', 'Second edition', (SELECT id FROM authors WHERE slug = 'alex-morgan'), (SELECT id FROM categories WHERE slug = 'programming'), 'Composable component patterns for large React applications.', 'A deep dive into composition, state, and performance in large React codebases.', 300, 'English', 'pdf', '978-1-00000-125-0', '2026-11-15', 'Advanced', 44900, 0, 'draft', 1, 0, '{"bg":"#14171B","fg":"#F6F4EE","accent":"#3654FF","pattern":"orbit"}', 'react-patterns-2027.pdf', '["react","frontend"]', '["Compose components cleanly","Manage state at scale","Profile and optimise renders"]', NULL),
  ('the-cartographers-daughter', 'The Cartographer''s Daughter', NULL, (SELECT id FROM authors WHERE slug = 'emma-wilson'), (SELECT id FROM categories WHERE slug = 'fiction'), 'A sweeping historical novel about maps, secrets, and a journey across oceans.', 'An adventure across three continents in search of a map that should never have been drawn.', 410, 'English', 'epub', '978-1-00000-126-7', '2026-12-01', 'All levels', 34900, 0, 'draft', 1, 0, '{"bg":"#FF5D5D","fg":"#F6F4EE","accent":"#14171B","pattern":"wave"}', 'the-cartographers-daughter.epub', '["historical fiction"]', '["An epic historical adventure"]', NULL);

COMMIT;
